### ISSUE TITLE
I can't get 2 sinden light guns to run 

### ISSUE THREAD

**Issue by richardprothype** [argonlefou/HotdRemake_ArcadePlugin#1]
Hi I can't get 2 sinden light guns to work what have I done wrong I have installed and set up Demulshooter and auto hotkey what have I missed the gun don't look like they are booting

**Comment by argonlefou** [comment]
I can't answer that question, not knowing what you did and not knowing the sinden that much....I can't say whats going wrong on your setup.

I highly advise you to seek help on Sinden discord for setting up you hardware

**Comment by richardprothype** [comment]
Thank you for getting back to me I found my problems there was 3 problems first was I didn't install the drivers properly, then the gun was not assented to the right functions and 3 I was using the wrong version of the autokey program I have now got it all to work as we need it

**Comment by richardprothype** [comment]
sorry I have another problem play 2 gun is shotting at the bottom left hand corner in the game when I have Demulshooter gui open it's showing the gun in the correct position even when the game is running in the back ground
