### ISSUE TITLE
Stops working after first cutscene

### ISSUE THREAD

**Issue by Davefromdenmark** [argonlefou/HotdRemake_ArcadePlugin#3]
Installed the patch.
Everythings works fine until first cutscene then the sinden lightgun stops working.

**Comment by argonlefou** [comment]
How many Sinden are you using for the game (1 or 2 ?)
Did you set up the `INPUT TYPE` as `SINGLE PLAYER` or `MULTIPLAYER` ?

What do you mean by "Sinden stops working" ?
Device is shut-off and you need to reboot ?
Buttons are not working ?
The gun does not control the aim in game but if you ALT-TAB it's still moving windows cursor ?
The gun does not move any cursor at all ?

**Comment by Davefromdenmark** [comment]
Thanx for quick reply.
I use only one gun (with recoil) and input is set as singleplayer.
The gun won’t fire and the calibration is way off. It only happens after the first cutscene (when sophie gets caught by the flying demon) until then everything works fine and the gun is accurate.
Sometimes I am able to get the gun to shoot a couple of times and if I shoot the 2 zombies (pure luck because the gun is way off) The gun will start to work again in the next scene however not as accurate as in the begining of the game (before first cutscene)
I have tried with the crosshair on and it just keep being in the same spot or sometimes moves just a little bit and I am then maybe able to shoot the 2 zombies and go on.

**Comment by argonlefou** [comment]
Thanks for the details.

SINGLE PLAYER mode is just using windows cursor position to aim at the game screen, so any pointing device would work the same for Player1

Next step would be to plug a mouse and test if the behaviour is the same with a mouse after the cut scene

**Comment by Davefromdenmark** [comment]
As you suggested I tried the game with a mouse and crosshair on. Everything worked fine. Then I knew it had to be an issue with the gun. I went through all the settings. When I made the border a bit thicker it worked!!! I played the game all night. Thank you so much! Great patch and very nice of you to help out. Thank you sir.
