### ISSUE TITLE
Mouse cursor is flashing on screen sometimes

### ISSUE THREAD

**Issue by MaximLopez** [argonlefou/HotdRemake_ArcadePlugin#7]
The in-game mouse cursor appears on the screen sometimes. It's sudden, like a flash.

I don't know if this is because my gun goes sometimes on screen or if the game is trying to recalculate the mouse cursor.

**Comment by MaximLopez** [comment]
Offscreen not on the screen !

**Comment by argonlefou** [comment]
Hi, 
I'm not sure to understand what is on-screeen / off-screen, with your edit ?

By in-game mosue cursor, are you talking about the window cursor (like, white arrow or "waiting" circle) ? Or about the in-game crosshait texture ?

**Comment by MaximLopez** [comment]
The in-game crosshair. And this is turned off in the settings of the mod

**Comment by argonlefou** [comment]
Is it COG release or steam version ?

**Comment by MaximLopez** [comment]
On both releases

**Comment by argonlefou** [comment]
Hmmm It's been a while since I did this. Isn't there an option in the updated STEAM (like, the game was out in April and there was an update in Jully) to hide crosshair ?

**Comment by MaximLopez** [comment]
This is possible in retail mode, but here it's not the cursor (the cross), but the mouse cursor that appears (the little arrow) :)

**Comment by argonlefou** [comment]
Ah ! 
In that case I don't know what can happen : the mouse cursor is handled by Windows and the fact that it can appear on screen suring the game can be related to a lot of things like..game flickering between fullscreen/window or graphics refresh or a lot of other rendering stuff

:(

**Comment by MaximLopez** [comment]
Thanks for fixing up the issue :)
