### ISSUE TITLE
Play as console mode with your arcade Mod ?

### ISSUE THREAD

**Issue by thebkooo** [argonlefou/HotdRemake_ArcadePlugin#9]
Hi,

the plugin works well with my Sinden, but is there a way to play the game with the console mode ? i would like to play without infinite credit.

Thanks

**Comment by argonlefou** [comment]
Hi,

No, this is an arcade mod so "console" play is not possible with that mod.

To play without infinite credits, you can just set FREEPLAY mode to OFF, and then stop adding credits once you want to stop.

If you really want the original game, you will need to follow your sinden wiki and use the Mystery Wizard patch:
https://www.sindenwiki.org/wiki/The_House_of_the_Dead_Remake#Dual_Lightgun_Patch_by_Mystery_Wizard_.28Outdated.29

**Comment by thebkooo** [comment]
Thanks for the information
